/**
 * scripts/generate-deck.js
 * 
 * Usage: node scripts/generate-deck.js <deck-id>
 * Example: node scripts/generate-deck.js rider-waite
 * 
 * Pre-requisite: Images must be in /assets/decks/<deck-id>/
 * Output: 
 *  - src/data/decks/<deck-id>/deck.json (Structure)
 *  - src/data/decks/<deck-id>/images.ts (Static Requires)
 *  - src/data/decks/<deck-id>/locales_template.json (Translation keys)
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error('Please provide a deck ID. Example: node scripts/generate-deck.js rider-waite');
  process.exit(1);
}

const DECK_ID = args[0];
const PROJECT_ROOT = path.resolve(__dirname, '..');
const ASSETS_DIR = path.join(PROJECT_ROOT, 'assets', DECK_ID);
const OUTPUT_DIR = path.join(PROJECT_ROOT, 'src', 'data', DECK_ID);

// Ensure asset directory exists
if (!fs.existsSync(ASSETS_DIR)) {
  console.error(`Error: Directory not found: ${ASSETS_DIR}`);
  console.error(`Please create the folder and add images first.`);
  process.exit(1);
}

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log(`Processing deck: ${DECK_ID}...`);

// --- 1. SCAN FILES ---
const files = fs.readdirSync(ASSETS_DIR).filter(f => /\.(jpg|jpeg|png|webp)$/i.test(f));
const cards = [];
const imageImports = [];
const translationKeys = {};

// Helper to determine metadata from filename
// Format: type_number_name.jpg (e.g., maj_00_fool.jpg, wands_01_ace.jpg)
const parseFile = (filename) => {
  const nameWithoutExt = filename.split('.')[0];
  const parts = nameWithoutExt.split('_'); // [type, number, name]

  let type = 'other';
  let suit = null;
  let number = 0;
  let id = nameWithoutExt; // Use filename as ID by default

  if (parts[0] === 'maj') {
    type = 'major';
    number = parseInt(parts[1], 10);
    // Standardize ID: maj_00
    id = `maj_${parts[1]}`;
  } else if (['wands', 'cups', 'swords', 'pentacles'].includes(parts[0])) {
    type = 'minor';
    suit = parts[0];
    number = parseInt(parts[1], 10);
    // Standardize ID: wands_01
    id = `${parts[0]}_${parts[1]}`;
  } else if (filename.startsWith('back')) {
    return { isBack: true, filename };
  }

  return {
    id,
    filename,
    meta: { type, suit, number }
  };
};

files.forEach(file => {
  const data = parseFile(file);
  
  if (data.isBack) {
    imageImports.push(`  'back_image': require('../../../../assets/${DECK_ID}/${file}'),`);
    return;
  }

  // Add to Deck Data
  cards.push({
    id: data.id,
    // image key for the images.ts map
    image: data.id, 
    meta: data.meta
  });

  // Add to Image Imports Map
  // Note: Path is relative to src/data/decks/<deck-id>/images.ts
  imageImports.push(`  '${data.id}': require('../../../../assets/${DECK_ID}/${data.filename}'),`);

  // Add to Translation Template
  translationKeys[data.id] = {
    name: `Card Name (${data.id})`,
    keywords: "keyword1, keyword2"
  };
});

// --- 2. SORT CARDS ---
// Order: Majors (0-21) -> Wands -> Cups -> Swords -> Pentacles
const suitOrder = { 'wands': 1, 'cups': 2, 'swords': 3, 'pentacles': 4 };

cards.sort((a, b) => {
  if (a.meta.type === 'major' && b.meta.type !== 'major') return -1;
  if (a.meta.type !== 'major' && b.meta.type === 'major') return 1;
  
  if (a.meta.type === 'major') {
    return a.meta.number - b.meta.number;
  } else {
    // Both are minors
    if (a.meta.suit !== b.meta.suit) {
      return suitOrder[a.meta.suit] - suitOrder[b.meta.suit];
    }
    return a.meta.number - b.meta.number;
  }
});

// Add sortIndex
cards.forEach((card, index) => {
  card.sortIndex = index;
});

// --- 3. GENERATE DECK.JSON ---
const deckJson = {
  info: {
    id: DECK_ID,
    totalCards: cards.length
  },
  cards: cards
};

fs.writeFileSync(
  path.join(OUTPUT_DIR, 'deck.json'), 
  JSON.stringify(deckJson, null, 2)
);
console.log(`✅ Generated deck.json (${cards.length} cards)`);

// --- 4. GENERATE IMAGES.TS ---
const imagesTsContent = `
// Auto-generated by scripts/generate-deck.js
const images: Record<string, any> = {
${imageImports.join('\n')}
};

export default images;
`;

fs.writeFileSync(
  path.join(OUTPUT_DIR, 'images.ts'), 
  imagesTsContent.trim()
);
console.log(`✅ Generated images.ts`);

// --- 5. GENERATE TRANSLATION TEMPLATE ---
const translationTemplate = {
  info: {
    name: "Deck Name",
    description: "Deck Description"
  },
  cards: translationKeys
};

fs.writeFileSync(
  path.join(OUTPUT_DIR, 'locales_template.json'), 
  JSON.stringify(translationTemplate, null, 2)
);
console.log(`✅ Generated locales_template.json (Copy this content to src/locales/...)`);

console.log(`\n🎉 Process complete for '${DECK_ID}'!`);